const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "Todo API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        User: {
            $email: "testUser123@gmail.com",
            $password: "123",
            
        },
        Users: {
            $name: "testUser123",
            $email: "testUser123@gmail.com",
            $password: "123",
        },

        Category: {
            name: "Gym",
        },
        
        CategoryEdit: {
            name: "Choose a new category name here!",
        },

        Todo: {
            name: "Todo created!",
            description: "A test for creating a todo",
            categoryId: "2",
            statusId: "1",
        },

        TodoEdit: {
            name: "Update the todo name here!",
            description: "Update the description here",
            categoryId: "Update id, example: 4",
            statusId: "Update status, example: 3",
        },


    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})
